### ISSUE TITLE
Getting error when building in AS: Unresolved reference: raw

### ISSUE THREAD

**Issue by dturner** [felipecsl/ktnes#3]
After following the build instructions I imported the ktnes project into Android Studio. 

When attempting to run the app on my Pixel XL (running Android 9.0 Pie) I get the following error: 

    e: /Users/donturner/Code/workspace-android/ktnes/android/app/src/main/kotlin/com/felipecsl/knes/app/MainActivity.kt: (148, 23): Unresolved reference: raw

**Comment by dturner** [comment]
Ah, I see this is a reference to a ROM file: 

    const val ROM = R.raw.legend_of_zelda

**Comment by dturner** [comment]
Might be worth updating the README with instructions on where to save your ROM file. i.e. 

`ktnes/android/app/src/main/res/raw`

Also, are there any legal ROMs which could be used for testing?

**Comment by felipecsl** [comment]
Good point, I'll fix that, should really add a file picker so you can use whatever ROM file you want.
You can find some public domain NES ROMs here https://www.zophar.net/pdroms/nes.html

**Comment by felipecsl** [comment]
This is fixed
